### ISSUE TITLE
Redmine 3.4 Compatibility

### ISSUE THREAD

**Issue by mnash04** [Restream/redmine_custom_reports#38]
Are there any plans to make this plugin compatible with 3.4?

**Comment by pablodav** [comment]
I have this error when trying it on redmine 3.4.3: 

```
  Rendered plugins/redmine_custom_reports/app/views/custom_reports/show.html.erb within layouts/base (34.6ms)
Completed 500 Internal Server Error in 45ms (ActiveRecord: 4.2ms)

ActionView::Template::Error (undefined method `issue_count_by_group' for #<QueryExt:0x007fc2b05b8b08>
Did you mean?  issue_count
               result_count_by_group):
    40:       <%= content_tag :div,
    41:         class:            'custom-report-chart',
    42:         style:            width_style_for_series(@custom_report),
    43:         'data-chart_data' => [series.data].to_json do %>
    44:         <h4><%= series.name %></h4>
    45:         <svg/>
    46:       <% end %>
  plugins/redmine_custom_reports/app/models/custom_report_series.rb:31:in `data_hash'
  plugins/redmine_custom_reports/app/models/custom_report_series.rb:18:in `data'
  plugins/redmine_custom_reports/app/views/custom_reports/show.html.erb:43:in `block (2 levels) in _plugins_redmine_custom_reports_app_views_custom_reports_show_html_erb___553947875689552176_70237081010940'
  plugins/redmine_custom_reports/app/views/custom_reports/show.html.erb:39:in `block in _plugins_redmine_custom_reports_app_views_custom_reports_show_html_erb___553947875689552176_70237081010940'
  plugins/redmine_custom_reports/app/views/custom_reports/show.html.erb:28:in `_plugins_redmine_custom_reports_app_views_custom_reports_show_html_erb___553947875689552176_70237081010940'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

**Comment by aavandry** [comment]
have the same issue with 3.4.3 as well
```
Environment:
  Redmine version                3.4.3.stable
  Ruby version                   2.2.8-p477 (2017-09-14) [x86_64-linux-gnu]
  Rails version                  4.2.8
...
Redmine plugins:
  redmine_contacts               4.1.1
```
```
  Rendered plugins/redmine_custom_reports/app/views/custom_reports/show.html.erb within layouts/base (34.3ms)                                                                                                                                
Completed 500 Internal Server Error in 86ms (ActiveRecord: 35.5ms)                                                                                                                                                                           
                                                                                                                                                                                                                                             
ActionView::Template::Error (undefined method `issue_count_by_group' for #<QueryExt:0x007fdd3158c8c8>):                                                                                                                                      
    32:     <% content_tag :div,                                                                                                                                                                                                             
    33:       class:            'custom-report-chart',                                                                                                                                                                                       
    34:       style:            width_style_for_series(@custom_report),                                                                                                                                                                      
    35:       'data-chart_data' => @custom_report.data.to_json do %>                                                                                                                                                                         
    36:       <svg/>                                                                                                                                                                                                                         
    37:     <% end %>                                                                                                                                                                                                                        
    38:   <% else %>                                                                                                                                                                                                                         
  plugins/redmine_custom_reports/app/models/custom_report_series.rb:31:in `data_hash'                                                                                                                                                        
  plugins/redmine_custom_reports/app/models/custom_report.rb:55:in `block in data'                                                                                                                                                           
  plugins/redmine_custom_reports/app/models/custom_report.rb:55:in `data'                                                                                                                                                                    
  plugins/redmine_custom_reports/app/views/custom_reports/show.html.erb:35:in `block in _plugins_redmine_custom_reports_app_views_custom_reports_show_html_erb___4288432463318117373_70293996871020'                                         
  plugins/redmine_custom_reports/app/views/custom_reports/show.html.erb:28:in `_plugins_redmine_custom_reports_app_views_custom_reports_show_html_erb___4288432463318117373_70293996871020'                                                  
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

**Comment by DikGatDolf** [comment]
Please note that the HEAD is now not compatible anymore with Redmine <v3.4, because of this change.

    Completed 500 Internal Server Error in 262ms (ActiveRecord: 109.3ms)
    
    ActionView::Template::Error (undefined method `result_count_by_group' for #<QueryExt:0x0000000531ce00>
    Did you mean?  issue_count_by_group):
        40:       <%= content_tag :div,
        41:         class:            'custom-report-chart',
        42:         style:            width_style_for_series(@custom_report),
        43:         'data-chart_data' => [series.data].to_json do %>
        44:         <h4><%= series.name %></h4>
        45:         <svg/>
        46:       <% end %>
      plugins/redmine_custom_reports/app/models/custom_report_series.rb:31:in `data_hash'
      plugins/redmine_custom_reports/app/models/custom_report_series.rb:18:in `data'
      plugins/redmine_custom_reports/app/views/custom_reports/show.html.erb:43:in `block (2 levels) in _31919db827b6cf$
      plugins/redmine_custom_reports/app/views/custom_reports/show.html.erb:39:in `block in _31919db827b6cf94bde7beb6e$
      plugins/redmine_custom_reports/app/views/custom_reports/show.html.erb:28:in `_31919db827b6cf94bde7beb6e95bf66b'
      lib/redmine/sudo_mode.rb:63:in `sudo_mode'

Usually the solution would be to just upgrade to the latest redmine version, but the Linux redmine-package is currently still at v3.2.
My interim solution was to revert to the 9 Aug 2016 commit (SHA: 46d5b2b) of the HEAD, which still works fine on redmine v3.2.

**Nonetheless, thanks for an awesome plugin!**

**Comment by luckygg** [comment]
have the same issue with 3.3.6 as well.

How can I solve it? ...

Please help me..

**Comment by jmtemmos** [comment]
Cannot edit or create any report:
Redmine version                3.4.6.stable.17449
  Ruby version                   2.4.2-p198 (2017-09-14) [x86_64-linux]
  Rails version                  4.2.8
  Environment                    production
  Database adapter               Mysql2


ActionView::Template::Error (undefined method `collect' for nil:NilClass):
    29:                 class: 'hidden-for-sighted' %>
    30:               <%= select_tag "#{filter_attr}op[#{field}]",
    31:                 options_for_select(
    32:                   operators_for_select(options[:type]),
    33:                   query.operator_for(field)),
    34:                 id:    "operators_#{field_id}",
    35:                 class: 'toggle_series_filter_operator' %>
  plugins/redmine_custom_reports/app/helpers/custom_reports_helper.rb:7:in `operators_for_select'
  plugins/redmine_custom_reports/app/views/custom_reports/_series_filters.html.erb:32:in `block in _565965ab419b4578d9e4043e30526e98'
  plugins/redmine_custom_reports/app/views/custom_reports/_series_filters.html.erb:7:in `each'
  plugins/redmine_custom_reports/app/views/custom_reports/_series_filters.html.erb:7:in `_565965ab419b4578d9e4043e30526e98'
  plugins/redmine_custom_reports/app/views/custom_reports/_series.html.erb:8:in `_5ca392b322d4ee401b505356a4984eed'
  plugins/redmine_custom_reports/app/views/custom_reports/_form.html.erb:52:in `block (2 levels) in _e8245eba17eaae03129fe15a5d6bd452'
  plugins/redmine_custom_reports/app/views/custom_reports/_form.html.erb:51:in `block in _e8245eba17eaae03129fe15a5d6bd452'
  app/helpers/application_helper.rb:1190:in `labelled_form_for'
  plugins/redmine_custom_reports/app/views/custom_reports/_form.html.erb:5:in `_e8245eba17eaae03129fe15a5d6bd452'
  plugins/redmine_custom_reports/app/views/custom_reports/new.html.erb:3:in `_b2f401971ab0af44feb6ef669673f881'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

**Comment by pablodav** [comment]
I have noticed, this plugin works on redmine 3.4 if I use git clone using master branch.

fix is on: https://github.com/Restream/redmine_custom_reports/commit/72ca6785ff3d73689a5944b52b4603209e5bfd13

**Comment by janekska** [comment]
I have version: 3.3.3 and have the same/similar problem.
For me works if in fix above there is "issue_count_by_group".
